drop database sys;
create database sys;
use sys;
CREATE TABLE EMPLOYEE (
    ID INT(7) NOT NULL UNIQUE AUTO_INCREMENT,
    FIRST_NAME VARCHAR(15) NOT NULL,
    MID_INIT VARCHAR(2),
    LAST_NAME VARCHAR(15) NOT NULL,
    STREET VARCHAR(20) NOT NULL,
    CITY VARCHAR(12) NOT NULL,
    STATE CHAR(2) NOT NULL,
    ZIP CHAR(5) NOT NULL,
    SSN INT(9) NOT NULL UNIQUE,
    START_DATE DATE,
    SUPERVISOR INT(7),
    PRIMARY KEY (ID),
    KEY (SSN)
);

CREATE TABLE BUS (
    ID INT(5) NOT NULL,
    CAPACITY INT(3) DEFAULT 1,
    START_DATE DATE,
    DRIVER INT(7) UNIQUE DEFAULT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (DRIVER)
        REFERENCES EMPLOYEE (ID)
);
CREATE TABLE CARD (
    ID INT(10) UNIQUE NOT NULL,
    BALANCE DECIMAL(5 , 2 ) NOT NULL DEFAULT 0,
    Expr_Date DATE NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE TAPS (
    B_ID INT(5) NOT NULL,
    C_ID INT(10) NOT NULL,
    Time_Stamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (B_ID , C_ID),
    FOREIGN KEY (B_ID)
        REFERENCES BUS (ID),
    FOREIGN KEY (C_ID)
        REFERENCES CARD (ID)
);
CREATE TABLE FARE_TIER (
    FARE_LEVEL VARCHAR(50) NOT NULL DEFAULT 'Adult fares (age 19-64)',
    FARE_COST DECIMAL(3 , 2 ) NOT NULL,
    CARD_ID INT(10) UNIQUE NOT NULL,
    PRIMARY KEY (FARE_LEVEL , FARE_COST),
    FOREIGN KEY (CARD_ID)
        REFERENCES CARD (ID),
    CONSTRAINT FARE_COST_TYPE CHECK (FARE_COST = (CASE
        WHEN
            FARE_LEVEL = 'Children age(0-5)'
                OR FARE_LEVEL = 'Senior/disabled fares (age 65+ or qualifying disability)'
        THEN
            0.00
        WHEN FARE_LEVEL = 'Youth fares (age 6-18)' THEN 2.75
        WHEN FARE_LEVEL = 'Adult fares (age 19-64)' THEN 3.25
    END)),
    CONSTRAINT FARE_LEVEL CHECK (FARE_LEVEL IN ('Children age(0-5)' , 'Youth fares (age 6-18)',
        'Senior/disabled fares (age 65+ or qualifying disability)',
        'Adult fares (age 19-64)'))
);
CREATE TABLE BUS_STOP(
	ID INT(4) UNIQUE NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    STREET1 VARCHAR(50) NOT NULL,
    STREET2 VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE ROUTE(
	ID INT(3) NOT NULL,
    ROUTE_NAME VARCHAR(10) NOT NULL,
    STREET1 VARCHAR(50) NOT NULL,
    STREET2 VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID, ROUTE_NAME)
);
CREATE TABLE VISIT(
	ROUTE_ID INT(3) NOT NULL,
    ROUTE_NAME VARCHAR(10) NOT NULL,
    BUS_STOP_ID INT(4) UNIQUE NOT NULL,
    TIME_ARRV TIME NOT NULL,
    TIME_DPRT TIME NOT NULL,
    PRIMARY KEY (ROUTE_ID, ROUTE_NAME, BUS_STOP_ID),
    FOREIGN KEY (ROUTE_ID, ROUTE_NAME) REFERENCES ROUTE(ID, ROUTE_NAME),
    FOREIGN KEY (BUS_STOP_ID) REFERENCES BUS_STOP(ID)    
);
CREATE TABLE TRAVERSE(
	R_NAME VARCHAR(10) NOT NULL,
    BUS_ID INT(5) NOT NULL,
    TIME_START TIME NOT NULL,
    TIME_END TIME NOT NULL,
    PRIMARY KEY (R_NAME, BUS_ID),
	FOREIGN KEY (BUS_ID) REFERENCES BUS(ID)    
);



